### ISSUE TITLE
p.134, 4-4: セル指定のタプル

### ISSUE THREAD

**Issue by kyama0321** [katsuhisa91/python_excel_book#4]
書籍 p.134 の "4-4: セルの値を編集する" の最後のコード例ですが，サンプルコード (update_cell.py) と同じように C1 のセルを更新するのであれば，
```python
wks.update_value((1,3), 150)
```
ですね．あくまで例の部分ですが， (3,1) のままだと日付の部分に値が入ってしまうので，コメントさせていただきました．

**Comment by Katsu1207** [comment]
@kyama0321 様
ご連絡ありがとうございます！たしかに、ご指摘のとおりですね。以下のように対応いたします。

1. 第三版の重版がかかった際には、修正させていただきます
2. [本サポートページのお知らせ](https://github.com/katsuhisa91/python_excel_book#%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B) に、ご指摘いただいた内容を追記いたします

読者の方から、こういったご連絡をいただけるのは、とても嬉しいです。
もし他になにか見つけていただいた際も、お気軽にご連絡ください。よろしくおねがいします。

**Comment by katsuhisa91** [comment]
@kyama0321 様
ご連絡ありがとうございます！たしかに、ご指摘のとおりですね。以下のように対応いたします。

 - 第三版の重版がかかった際には、修正させていただきます
 - 本サポートページのお知らせ に、ご指摘いただいた内容を追記いたします

読者の方から、こういったご連絡をいただけるのは、とても嬉しいです。
もし他になにか見つけていただいた際も、お気軽にご連絡ください。よろしくおねがいします。
