### ISSUE TITLE
p.227 7-3 scraping/get_python_books.py の URL 表示

### ISSUE THREAD

**Issue by kyama0321** [katsuhisa91/python_excel_book#5]
p.227 7-3 "Web スクレイピングでデータを取得する" において、GitHub で公開されている scraping/get_python_books.py の22行目の URL が、書籍に記載されているものと異なっています。
```python
print('https://gihyo.jp/book/genre' + book_url)
```
上記だと、リンク先がエラーになってしまいますので、書籍の記載通り
```python
print('https://gihyo.jp' + book_url)
```
に修正すれば、ちゃんと表示されました。

**Comment by katsuhisa91** [comment]
先日に引き続き、ご報告ありがとうございます！とても嬉しいです。
サポートページのサンプルプログラムを、Pull Request出して修正します！

**Comment by katsuhisa91** [comment]
修正しました、ご指摘ありがとうございました！
