### ISSUE TITLE
'trello_archive/README.md' APIの新規ドキュメントのURL

### ISSUE THREAD

**Issue by kyama0321** [katsuhisa91/python_excel_book#8]
「8-2 Web APIで、Trelloのデータを取得・操作する」が記述されているファイル (https://github.com/katsuhisa91/python_excel_book/blob/master/trello_archive/README.md) 内のAPIドキュメントに関するページがUIとURLともに更新されているようです。

README.mdの内容に合わせると以下のようになっていました。

- ホーム画面: 
    - (旧) https://developers.trello.com/reference/ (旧) → (新) にリダイレクトかかる
    - (新) https://developer.atlassian.com/cloud/trello/rest/

- membersidboards
    - (旧) https://developers.trello.com/reference/#membersidboards  (旧) → ホーム画面にリダイレクトかかる
    - (新) https://developer.atlassian.com/cloud/trello/rest/api-group-members/#api-members-id-boards-get

**Comment by katsuhisa91** [comment]
ご連絡ありがとうございます！おお、たしかにそう変更されていますね…
API の仕様そのものが変わったわけではないので、プログラムの動作に影響はないとは思うのですが、本文のURLやスクリーンショットの修正が必要だと思うので、順次対応します。
ご連絡ありがとうございます！

**Comment by katsuhisa91** [comment]
修正しました、ご報告ありがとうございました！
https://github.com/katsuhisa91/python_excel_book/commit/ab6d26b14d0c45b087517c4a39d9b747d17d23cb

**Comment by kyama0321** [comment]
> API の仕様そのものが変わったわけではないので、プログラムの動作に影響はないとは思うのですが

はい、影響ありません。

おかげさまで連休中に本書を一気にやり切ることができました！文章もサンプルコードも非常に読みやすい上に、読者特典の内容も参考になりました😁

**Comment by katsuhisa91** [comment]
ありがとうございます！とても嬉しいです！
今後もなにかあればお気軽にご連絡いただければ嬉しいです。
